---
title: Scraping el congreso de los diputados
author: Pablo Ugarte
date: '2017-09-23'
slug: scraping-el-congreso-de-los-diputados
categories: []
tags: []
---

# Intro

>In this post, we scrape data and data wrangle to get a picture of type oj jobs offered in the expansion website.

# Libraries

Overall, we are going to use the following R packages:

```{r, message = FALSE, warning = FALSE}
library(XML) # For web scraping
library(rvest) # For web scraping
library(tidyverse) # Data wrangling packages gather, spread...
library(lubridate) # To work with dates
library(hrbrthemes) # Aesthetic defaults for ggplot2 charts
library(stringr) # For manipulating strings
```

```{r, message = FALSE, warning = FALSE}
curriculos = ""
for (dip in seq(1,20,by=1)) {
url = paste0("http://www.congreso.es/portal/page/portal/Congreso/Congreso/Diputados/BusqForm?_piref73_1333155_73_1333154_1333154.next_page=/wc/fichaDiputado?idDiputado=",dip,"&idLegislatura=12")
 
curric <- read_html(url) %>% 
          html_node("#curriculum") %>%
          html_text %>%
          strsplit(split = "\n") %>% #Particionamos el texto en función de los /n
          unlist() %>%
          .[. != ""]

#Quitamos espacios en blanco, tabuladores y saltos de línea
curric <- trimws(curric)
#Elimina las líneas sin contenido
curric <- curric[which(curric!="")]
#Nos quedamos justo con la linea que hay debajo de la palabra legislatura
line_after_legislatura <- curric[grep("legislatura", curric)+1]
#Acumulamos las líneas con la formación de cada diputado
curriculos <- rbind(curriculos,line_after_legislatura) }
#Creamos el data frame
curriculos <- data.frame(curriculos)
#Quitamos la primera linea, que esta vacia
curriculos <- curriculos  %>% slice(2:n())
View(curriculos)
```

```{r, message = FALSE, warning = FALSE}
#El texto lo transformamos en una lista separada por espacios
palabras <-strsplit(curriculos, split=" ")
#Deshacemos esa lista y tenemos el data.frame
palabras <- as.character(unlist(palabras))
palabras <- data.frame(palabras)
names(palabras) <- c("V1")
#Eliminamos algunos caracteres regulares
palabras$V1 = sub("([[:space:]])","",palabras$V1)
palabras$V1 = sub("([[:digit:]])","",palabras$V1)
palabras$V1 = sub("([[:punct:]])","",palabras$V1)

```

